# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e54dd66ca93c562c7ebf93c4099020024578ca907411394b3837275bed2e0d240b82bbc498682931efb7093bf6a368af00c2d2b112cce422f5e165e1b88e03d2

test:
  secret_key_base: 81ffd2ae392cdbb681ff66d298a774f79fa8340c30a615a76986dda330c57e2bb2605805c92d651f8a3b23605632fecc573a62288fdefb8ece3d5620b1e3109b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
